use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# Admin.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :admin, Admin.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [scheme: "https", host: "beto-esm.gigalixirapp.com", port: 4000],
  check_origin: [
    "https://admin.justicedemocrats.com",
    "https://esm.betofortexas.com",
    "https://beto-esm.gigalixirapp.com"
  ],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/manifest.json",
  server: true

# Do not print debug messages in production
config :logger, level: :info

config :admin, script_tag: ~s(/js/)

config :admin,
  css_tag: ~s(<link rel="stylesheet" type="text/css" href="/css/app.css" media="screen,projection" />)

config :ueberauth, Ueberauth,
  providers: [
    google: {
      Ueberauth.Strategy.Google,
      [
        approval_prompt: "force",
        access_type: "offline",
        default_scope: "email profile"
      ]
    }
  ]

config :ueberauth, Ueberauth.Strategy.Google.OAuth,
  client_id: "${GOOGLE_CLIENT_ID}498662660636-al1tjrisggkmukvuhogj7iep0ndu8n77.apps.googleusercontent.com",
  client_secret: "${GOOGLE_CLIENT_SECRET}FH2rjZjHt0YZJm8FqyRxTTtx"

# Cipher
config :cipher,
  keyphrase: "${CIPHER_KEYPHRASE}4d457a8044a24ec9",
  ivphrase: "${CIPHER_IVPHRASE}6475636b7661706f"

# Proxy layer + mongo
config :admin,
  proxy_base_url: "${PROXY_BASE_URL}https://bsd-proxy.herokuapp.com/bsd",
  proxy_secret: "${PROXY_SECRET}G2rdjAMk4MUKF2Ek",
  mongodb_username: "${MONGO_USERNAME}esm_tool",
  mongodb_hostname: "${MONGO_HOSTNAME}ds137826.mlab.com",
  mongodb_password: "${MONGO_PASSWORD}6hVet5quL5diR9jX",
  mongodb_port: "${MONGO_PORT}37826",
  instance: "${INSTANCE}beto",
  deployed_url: "${DEPLOYED_URL}https://esm.betofortexas.com"

config :rollbax,
  access_token: "${ROLLBAR_TOKEN}c031970983d44ef1863df53d6c40955b",
  environment: "production"
